[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm install', 'npm install --prefix backend']

[phases.build]
cmds = ['npm --prefix frontend run build']

[start]
cmd = 'cd backend && npx ts-node src/server.ts'